nodes:
  VM1:
    openstack_node: vm1
    hostname: controller
    interfaces:
      management: # Mandatory
        ip: 192.168.110.10
        netmask: 255.255.255.0
      traffic:
        ip: 192.168.120.10
        netmask: 255.255.255.0
    user: stack
    password: stack
    root_password: password
    #image: /opt/stack/images/xenial_cloudimg.img
    image: /opt/stack/images/bionic-server-cloudimg-amd64.img
    disk: 8000
    ram: 2000
    vcpus: 4
  VM2:
    openstack_node: vm1
    hostname: controller
    interfaces:
      management: # Mandatory
        ip: 192.168.220.11
        netmask: 255.255.255.0
      traffic:
        ip: 192.168.230.11
        netmask: 255.255.255.0
    user: stack
    password: stack
    root_password: password
    #image: /opt/stack/images/xenial_cloudimg.img
    image: /opt/stack/images/bionic-server-cloudimg-amd64.img
    disk: 12000
    ram: 8192
    vcpus: 2

networks:
  management: # Mandatory
    default_gateway: True
    host_ip: 192.168.110.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.110.200
    dhcp_ip_end: 192.168.110.250

  traffic:
    default_gateway: False # This parameter is not mandatory, default value: False
    host_ip: 192.168.120.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.120.200
    dhcp_ip_end: 192.168.120.250

#END

