nodes:
  VM1:
    openstack_node: vm1
    hostname: controller
    openstack_role: controller_allinone
    interfaces:
      infra_mgt: # Mandatory, do not change the name
        ip: 192.168.110.10
        netmask: 255.255.255.0
      infra_tenant:
        ip: 192.168.120.10
        netmask: 255.255.255.0
      infra_ext:
        ip: 192.168.130.10
        netmask: 255.255.255.0
    user: stack
    password: stack
    root_password: password
    #image: /opt/stack/images/focal-server-cloudimg-amd64-disk-kvm.img
    image: /opt/stack/images/bionic-server-cloudimg-amd64.img
    disk: 20000
    ram: 8192
    vcpus: 2
#  VM2:
#    openstack_node: vm2
#    hostname: compute
#    openstack_role: compute
#    interfaces:
#      infra_mgt: # Mandatory, do not change the name
#        ip: 192.168.110.20
#        netmask: 255.255.255.0
#      infra_tenant:
#        ip: 192.168.120.20
#        netmask: 255.255.255.0
#      infra_ext:
#        ip: 192.168.130.20
#        netmask: 255.255.255.0
#    user: stack
#    password: stack
#    root_password: password
#    image: /opt/stack/images/focal-server-cloudimg-amd64-disk-kvm.img
#    disk: 20000
#    ram: 8192
#    vcpus: 2

networks:
  infra_mgt: # Mandatory, do not change the name
    default_gateway: True
    host_ip: 192.168.110.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.110.200
    dhcp_ip_end: 192.168.110.250
  infra_tenant:
    default_gateway: False # This parameter is not mandatory, default value: False
    host_ip: 192.168.120.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.120.200
    dhcp_ip_end: 192.168.120.250
  infra_ext:
    default_gateway: False # This parameter is not mandatory, default value: False
    host_ip: 192.168.130.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.130.200
    dhcp_ip_end: 192.168.130.250

#END
