nodes:
  VM1:
    openstack_node: vm1
    hostname: controller
    interfaces:
      infra_mgt: # Mandatory, do not change the name
        ip: 192.168.110.10
        netmask: 255.255.255.0
      infra_traffic1:
        ip: 192.168.120.10
        netmask: 255.255.255.0
    user: stack
    password: stack
    root_password: password
    #image: /opt/stack/images/bionic-server-cloudimg-amd64.img
    #image: /opt/stack/images/Fedora-Cloud-Base-31-1.9.x86_64.raw
    image: /opt/stack/images/focal-server-cloudimg-amd64-disk-kvm.img
    disk: 20000
    ram: 8192
    vcpus: 2
  VM2:
    openstack_node: vm2
    hostname: compute
    interfaces:
      infra_mgt: # Mandatory, do not change the name
        ip: 192.168.110.20
        netmask: 255.255.255.0
      infra_traffic1:
        ip: 192.168.120.20
        netmask: 255.255.255.0
    user: stack
    password: stack
    root_password: password
    image: /opt/stack/images/focal-server-cloudimg-amd64-disk-kvm.img
    disk: 20000
    ram: 8192
    vcpus: 2

networks:
  infra_mgt: # Mandatory, do not change the name
    default_gateway: True
    host_ip: 192.168.110.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.110.200
    dhcp_ip_end: 192.168.110.250

  infra_traffic1:
    default_gateway: False # This parameter is not mandatory, default value: False
    host_ip: 192.168.120.1
    netmask: 255.255.255.0
    dhcp_ip_start: 192.168.120.200
    dhcp_ip_end: 192.168.120.250

#END
